### ISSUE TITLE
Benefits/ strengths of ntcn_ocr ? [question]

### ISSUE THREAD

**Issue by mrocr** [mittagessen/ntcn_ocr#1]
@mittagessen thank you for your hard work

- What benefits does ntcn_ocr have, what are you trying to achieve?
- Does it have similar concept to[ parallel wavenet](https://youtu.be/hzpxXZJQNFg?t=71)?

**Comment by mittagessen** [comment]
It was a fully convolutional line recognizer with dilated convolutions in the past. The main purpose was to see if a faster network without recurrent layers performs better than the CNN-LSTM in kraken. It works but the accuracy is below RNNs for heavily degraded data.

At some point I started trying the reimplement the Kaldi chain networks without the LM modelling component as somebody showed me really impressive results. Unfortunately, most of their improvement seems to originate from the language modelling, although I haven't implemented their loss function and training scheme and just train with plain Adam and CTC.
